server:
  port: 629

spring:
  application:
    name: saobao
  data:
    redis:
      host: 192.168.153.101
      port: 6379
      password: 123456

langchain4j:
  open-ai:
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-fbf72a617bf140c5a3754086ed1ad7bd
      model-name: qwen-flash
      log-responses: true
      log-requests: true
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-fbf72a617bf140c5a3754086ed1ad7bd
      model-name: qwen-flash
      log-responses: true
      log-requests: true

logging:
  level:
    dev.langchain4j: DEBUG